---
apiVersion: v1    
kind: Secret
metadata:
  name: mysql-secret
  namespace: sanovi
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ= #password
  MYSQL_DATABASE: dGVzdA== #test
  MYSQL_USER: dGVzdHVzZXI= #testuser
  MYSQL_PASSWORD: dGVzdDEyMw== #test123
---
apiVersion: v1
kind: Pod
metadata:
  name: spring-mysql
  namespace: sanovi
  labels:
    app: spring-mysql
spec:
    containers:
    - image: mysql:5.7
      name: mysql
      env:
        # Use secret in real usage
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_ROOT_PASSWORD
      - name: MYSQL_DATABASE
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_DATABASE
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_USER
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_PASSWORD          
      ports:
      - containerPort: 3306
        name: mysql
    - name: spring-mysql
      image: index.docker.io/neethirocks/spring-mysql:1.0
      ports:
        - containerPort: 8080
      env:
      - name: spring_jpa_database
        value: mysql
      - name: spring_datasource_url
        value: jdbc:mysql://127.0.0.1:3306/test?useSSL=false
      - name: spring_datasource_username
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_USER
      - name: spring_datasource_password
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_PASSWORD
      readinessProbe:
          exec:
            command: ['sh', '-c', 'until nslookup 127.0.0.1; do echo waiting for mysql; sleep 2; done;']            
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
    initContainers:
    - name: init-myservice
      image: busybox:1.28
      command: ['sh', '-c', 'until nslookup 127.0.0.1; do echo waiting for mysql; sleep 2; done;'] 
            

---
apiVersion: v1
kind: Service
metadata:
  name: spring-mysql-service
  namespace: sanovi
  labels:
    name: spring-mysql-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: spring-mysql
  type: NodePort
