---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mstr-mysqlinitcmap
  namespace: default
data:
  initdb.sql: |-
    grant all privileges on *.* to root@localhost identified by 'password' with grant option;
    flush privileges;
---
apiVersion: v1    
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ= #password
  MYSQL_DATABASE: dGVzdA== #test
  MYSQL_USER: dGVzdHVzZXI= #testuser
  MYSQL_PASSWORD: dGVzdDEyMw== #test123
---
apiVersion: v1
kind: Pod
metadata:
  name: spring-mysql
  labels:
    app: spring-mysql
spec:
    volumes:
    - name: mstr-mysqlinitcmap-vol
      configMap:
        name: mstr-mysqlinitcmap
    containers:
    - image: mysql:5.7
      name: mysql
      env:
      - name: MYSQL_PWD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_ROOT_PASSWORD            
        # Use secret in real usage
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_ROOT_PASSWORD
      - name: MYSQL_DATABASE
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_DATABASE
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_USER
      - name: MYSQL_PWD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_ROOT_PASSWORD      
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_PASSWORD          
      ports:
      - containerPort: 3306
        name: mysql
      volumeMounts:
      - name: mstr-mysqlinitcmap-vol
        mountPath: /docker-entrypoint-initdb.d
        
    - name: spring-mysql
      image: index.docker.io/neethirocks/spring-mysql:2.0
      ports:
        - containerPort: 8080
      env:
      - name: spring_jpa_database
        value: mysql
      - name: spring_datasource_url
        value: jdbc:mysql://127.0.0.1:3306/test?useSSL=false
      - name: spring_datasource_username
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_USER
      - name: spring_datasource_password
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_PASSWORD
      readinessProbe:
          exec:
            command: ['sh', '-c', 'until nslookup 127.0.0.1; do echo waiting for mysql; sleep 2; done;']            
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
---
apiVersion: v1
kind: Service
metadata:
  name: spring-mysql-service
  labels:
    name: spring-mysql-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: spring-mysql
  type: NodePort
