---
apiVersion: v1    
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ= #password
  MYSQL_DATABASE: dGVzdA== #test
  MYSQL_USER: dGVzdHVzZXI= #testuser
  MYSQL_PASSWORD: dGVzdDEyMw== #test123
---
apiVersion: v1
kind: Pod
metadata:
  name: spring-mysql
  labels:
    app: spring-mysql
spec:
    volumes:
    - name: mysql-persistent-storage
      persistentVolumeClaim:
        claimName: mysql-pv-claim
    containers:
    - image: mysql:5.7
      name: mysql
      env:
        # Use secret in real usage
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_ROOT_PASSWORD
      - name: MYSQL_DATABASE
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_DATABASE
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_USER
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_PASSWORD          
      ports:
      - containerPort: 3306
        name: mysql
      volumeMounts:
      - name: mysql-persistent-storage
        mountPath: /var/lib/mysql
      livenessProbe:
        exec:
          command: ["mysqladmin", "ping"]
        initialDelaySeconds: 30
        periodSeconds: 10
        timeoutSeconds: 5
      readinessProbe:
          exec:
            # Check we can execute queries over TCP (skip-networking is off).
            command: ["mysql", "-h", "127.0.0.1", "-u $MYSQL_USER -p $MYSQL_PASSWORD", "-e", "SELECT 1"]
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
    - name: spring-mysql
      image: index.docker.io/neethirocks/spring-mysql:1.0
      ports:
        - containerPort: 8080
      env:
      - name: spring_jpa_database
        value: mysql
      - name: spring_datasource_url
        value: jdbc:mysql://127.0.0.1:3306/test?useSSL=false
      - name: spring_datasource_username
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_USER
      - name: spring_datasource_password
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: spring-mysql-service
  labels:
    name: spring-mysql-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: spring-mysql
  type: NodePort
