---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysqlinit
  namespace: default
data:
  initdb.sql: |
    CREATE TABLE aadhaar ( name varchar(255) NOT NULL, 
    sex char NOT NULL, birth DATE  NOT NULL, death DATE  NULL,
    id int(255) NOT NULL AUTO_INCREMENT, PRIMARY KEY (id) );
---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: myconfmap
  namespace: default
data:
  mysqld.cnf: |
    [mysqld]
    log-bin=/var/lib/mysql/mysql-bin
    server-id=2
    replicate-do-db=test
    relay-log=/var/lib/mysql/mysql-relay-bin
    relay-log-index=/var/lib/mysql/mysql-relay-bin.index
    master-info-file=/var/lib/mysql/mysql-master.info
    relay-log-info-file=/var/lib/mysql/mysql-relay-log.info
---
---
apiVersion: v1    
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ= #password
  MYSQL_DATABASE: dGVzdA== #test
  MYSQL_USER: dGVzdHVzZXI= #testuser
  MYSQL_PASSWORD: dGVzdDEyMw== #test123
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv1-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data1"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv1-claim
  labels:
   app: mysql-storage-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate      
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_SERVER_CONTAINER
          value: mysql
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD          
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysqlinitconf
          mountPath: /docker-entrypoint-initdb.d
        - name: myconf
          mountPath: /etc/mysql/mysql.conf.d/mysqld.cnf
          subPath: mysqld.cnf
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv1-claim
      - name: myconf
        configMap:
          name: myconfmap
      - name: mysqlinitconf
        configMap:
          name: mysqlinit
